name: CI (Windows, unittest)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps (optional)
        if: hashFiles('**/requirements*.txt') != ''
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Set PYTHONPATH
        shell: pwsh
        run: |
          $env:PYTHONPATH = "$(Get-Location)"
          echo "PYTHONPATH=$env:PYTHONPATH" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Run unit tests
        shell: pwsh
        run: |
          cd .\lastivka_core\unit_tests
          python -m unittest -v

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lastivka-logs
          path: |
            lastivka_core/logs/**/*.log
            lastivka_core/logs/**/*.json
          if-no-files-found: ignore
